import type { ChallengeConfig, ChallengeManifest } from '../types/challenge';

const challengeLoaders: Record<string, () => Promise<{ default: ChallengeConfig }>> = {
  'normalize-customer-orders': () => import('./normalize-customer-orders/config'),
  'single-index-for-lookup': () => import('./single-index-for-lookup/config'),
  'composite-index-column-order': () => import('./composite-index-column-order/config'),
  'fix-n-plus-one': () => import('./fix-n-plus-one/config'),
  'enforce-referential-integrity': () => import('./enforce-referential-integrity/config'),
  'latest-per-group-subquery': () => import('./latest-per-group-subquery/config'),
  'cte-and-set-operations-report': () => import('./cte-and-set-operations-report/config'),
  'keyset-pagination': () => import('./keyset-pagination/config'),
  'upsert-on-conflict': () => import('./upsert-on-conflict/config'),
  'atomic-stock-transaction': () => import('./atomic-stock-transaction/config'),
  'expression-index-for-login': () => import('./expression-index-for-login/config'),
  'dedupe-and-add-unique': () => import('./dedupe-and-add-unique/config'),
  'backfill-derived-column': () => import('./backfill-derived-column/config'),
  'archive-old-rows': () => import('./archive-old-rows/config'),
  'repair-orphaned-rows': () => import('./repair-orphaned-rows/config'),
  'least-privilege-app-user': () => import('./least-privilege-app-user/config'),
};

export const challengeManifest: ChallengeManifest[] = [
  {
    slug: 'normalize-customer-orders',
    title: '顧客・注文テーブルの正規化',
    description: '1枚の非正規化テーブルを3NFまで分解し、外部キーで関連付ける',
    icon: 'Database',
    color: 'sky',
    badge: 'DB設計',
    path: '/challenges/normalize-customer-orders',
    dialects: ['postgres', 'mysql'],
  },
  {
    slug: 'single-index-for-lookup',
    title: '遅い検索クエリに単一インデックスを追加する',
    description: 'EXPLAINでSeq Scanを確認し、適切な単一インデックスで解消する',
    icon: 'ListTree',
    color: 'blue',
    badge: '単一インデックス',
    path: '/challenges/single-index-for-lookup',
    dialects: ['postgres', 'mysql'],
  },
  {
    slug: 'composite-index-column-order',
    title: '複合インデックスの列順序を最適化する',
    description: 'WHERE句とORDER BYの両方を活かせる列順序を見極める',
    icon: 'Rows3',
    color: 'indigo',
    badge: '複合インデックス',
    path: '/challenges/composite-index-column-order',
    dialects: ['postgres', 'mysql'],
  },
  {
    slug: 'fix-n-plus-one',
    title: 'N+1クエリをJOINで解消する',
    description: '繰り返し発行されていた問い合わせを1本のJOINクエリに書き換える',
    icon: 'Gauge',
    color: 'amber',
    badge: 'パフォーマンス',
    path: '/challenges/fix-n-plus-one',
    dialects: ['postgres', 'mysql'],
  },
  {
    slug: 'enforce-referential-integrity',
    title: '壊れたスキーマに制約を追加する',
    description: 'NOT NULL・外部キー・CHECK制約でデータ不整合を防ぐ',
    icon: 'ShieldCheck',
    color: 'emerald',
    badge: '制約周り',
    path: '/challenges/enforce-referential-integrity',
    dialects: ['postgres', 'mysql'],
  },
  {
    slug: 'latest-per-group-subquery',
    title: 'グループごとの最新レコードを取得する',
    description: '相関サブクエリまたはウィンドウ関数でグループ最新行を1件ずつ抽出する',
    icon: 'GitMerge',
    color: 'purple',
    badge: 'サブクエリ',
    path: '/challenges/latest-per-group-subquery',
    dialects: ['postgres', 'mysql'],
  },
  {
    slug: 'cte-and-set-operations-report',
    title: 'CTEと集合演算で複合レポートを作る',
    description: '複数の集計をCTEで整理し、UNIONで1つのレポートにまとめる',
    icon: 'GitMerge',
    color: 'purple',
    badge: 'サブクエリ',
    path: '/challenges/cte-and-set-operations-report',
    dialects: ['postgres', 'mysql'],
  },
  {
    slug: 'keyset-pagination',
    title: '深いページも速いページネーションを作る',
    description: 'OFFSETページングの弱点を、複合インデックス+カーソル(keyset)方式で解消する',
    icon: 'ArrowDownWideNarrow',
    color: 'sky',
    badge: 'Web開発',
    path: '/challenges/keyset-pagination',
    dialects: ['postgres', 'mysql'],
  },
  {
    slug: 'upsert-on-conflict',
    title: '設定保存APIをUPSERTで実装する',
    description: '「あればUPDATE、なければINSERT」をON CONFLICTで1文にまとめ、レースコンディションを排除する',
    icon: 'Save',
    color: 'emerald',
    badge: 'Web開発',
    path: '/challenges/upsert-on-conflict',
    dialects: ['postgres'],
  },
  {
    slug: 'atomic-stock-transaction',
    title: '在庫の売り越しを防ぐ',
    description: 'CHECK制約と条件付きUPDATEで、同時購入でも在庫がマイナスにならない引き当てを作る',
    icon: 'PackageCheck',
    color: 'amber',
    badge: 'Web開発',
    path: '/challenges/atomic-stock-transaction',
    dialects: ['postgres'],
  },
  {
    slug: 'expression-index-for-login',
    title: 'リリース後にログインが遅くなった',
    description: '関数で包んだWHERE句はインデックスが効かない。式インデックスで解消する',
    icon: 'LogIn',
    color: 'blue',
    badge: 'リリース直後',
    path: '/challenges/expression-index-for-login',
    dialects: ['postgres', 'mysql'],
  },
  {
    slug: 'dedupe-and-add-unique',
    title: '二重登録データを掃除してUNIQUEで再発防止する',
    description: 'ボタン連打で生まれた重複行を最初の1件だけ残して削除し、一意制約で塞ぐ',
    icon: 'CopyX',
    color: 'indigo',
    badge: 'リリース直後',
    path: '/challenges/dedupe-and-add-unique',
    dialects: ['postgres', 'mysql'],
  },
  {
    slug: 'backfill-derived-column',
    title: '稼働中テーブルに列を追加してバックフィルする',
    description: 'NULL許容で追加→既存データから埋める→NOT NULL化、の安全な3段階マイグレーション',
    icon: 'Columns3',
    color: 'purple',
    badge: '運用',
    path: '/challenges/backfill-derived-column',
    dialects: ['postgres'],
  },
  {
    slug: 'archive-old-rows',
    title: '肥大化したテーブルをアーカイブする',
    description: '古い既読通知をアーカイブテーブルへ移動し、現役テーブルを軽く保つ',
    icon: 'Archive',
    color: 'orange',
    badge: '運用',
    path: '/challenges/archive-old-rows',
    dialects: ['postgres', 'mysql'],
  },
  {
    slug: 'repair-orphaned-rows',
    title: '孤児行を調査・修復して外部キーで塞ぐ',
    description: '退会処理のバグで生まれた「親のいない注文」を特定して掃除し、FKで再発防止する',
    icon: 'Wrench',
    color: 'emerald',
    badge: '障害対応',
    path: '/challenges/repair-orphaned-rows',
    dialects: ['postgres'],
  },
  {
    slug: 'least-privilege-app-user',
    title: '読み取り専用ロールを最小権限で作る',
    description: 'CREATE ROLEとGRANTで、機微テーブルに触れないサポート用ロールを設計する',
    icon: 'UserCog',
    color: 'sky',
    badge: '権限',
    path: '/challenges/least-privilege-app-user',
    dialects: ['postgres'],
  },
];

export async function loadChallengeConfig(slug: string): Promise<ChallengeConfig> {
  const loader = challengeLoaders[slug];
  if (!loader) throw new Error(`Unknown challenge: ${slug}`);
  const module = await loader();
  return module.default;
}
